<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-12 12:38

$extensionPath = t3lib_extMgm::extPath('themes');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themes_domain_model_theme' => $extensionClassesPath . 'Domain/Model/Theme.php',
	'tx_themes_domain_repository_themerepository' => $extensionClassesPath . 'Domain/Repository/ThemeRepository.php',
	'tx_themes_t3libtstemplateincludestatictyposcriptsourcesatendhook' => $extensionClassesPath . 'Hook/T3libTstemplateIncludeStaticTypoScriptSourcesAtEndHook.php',
	'tx_themes_tca_themeselector' => $extensionClassesPath . 'Tca/ThemeSelector.php',
	'tx_themes_templatemodulebodypostprocesshook' => $extensionClassesPath . 'Hook/TemplateModuleBodyPostProcessHook.php',
);
?>