<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-09 04:40

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('themes');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themes_configuration_extensionstest' => $extensionPath . 'Tests/Unit/Configuration/ExtensionsTest.php',
	'tx_themes_domain_model_theme' => $extensionClassesPath . 'Domain/Model/Theme.php',
	'tx_themes_domain_model_themetest' => $extensionPath . 'Tests/Unit/Domain/Model/ThemeTest.php',
	'tx_themes_domain_repository_themerepository' => $extensionClassesPath . 'Domain/Repository/ThemeRepository.php',
	'tx_themes_domain_repository_themerepositorytest' => $extensionPath . 'Tests/Unit/Domain/Repository/ThemeRepositoryTest.php',
	'tx_themes_hook_pagenotfoundhandlinghook' => $extensionClassesPath . 'Hooks/PageNotFoundHandlingHook.php',
	'tx_themes_hook_themesdomainrepositorythemerepositoryinithook' => $extensionClassesPath . 'Hooks/ThemesDomainRepositoryThemeRepositoryInitHook.php',
	'tx_themes_t3libtstemplateincludestatictyposcriptsourcesatendhook' => $extensionClassesPath . 'Hooks/T3libTstemplateIncludeStaticTypoScriptSourcesAtEndHook.php',
	'tx_themes_tca_themeselector' => $extensionClassesPath . 'Tca/ThemeSelector.php',
	'tx_themes_templatemodulebodypostprocesshook' => $extensionClassesPath . 'Hooks/TemplateModuleBodyPostProcessHook.php',
	'tx_themes_preheaderrenderhook' => $extensionClassesPath . 'Hooks/PreHeaderRenderHook.php',
	'tx_themes_viewhelpers_widget_languagemenuviewhelper' => $extensionClassesPath . 'ViewHelpers/Widget/LanguageMenuViewHelper.php',
	'tx_themes_viewhelpers_widget_controller_languagemenucontroller' => $extensionClassesPath . 'ViewHelpers/Widget/Controller/LanguageMenuController.php',
);
?>