<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-02 20:52

$extensionPath = t3lib_extMgm::extPath('themes');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themes_domain_model_skin' => $extensionClassesPath . 'Domain/Model/Skin.php',
	'tx_themes_domain_repository_skinrepository' => $extensionClassesPath . 'Domain/Repository/SkinRepository.php',
	'tx_themes_t3libtstemplateincludestatictyposcriptsourcesatendhook' => $extensionClassesPath . 'Hook/T3libTstemplateIncludeStaticTypoScriptSourcesAtEndHook.php',
	'tx_themes_tca_skinselector' => $extensionClassesPath . 'Tca/Skinselector.php',
	'tx_themes_templatemodulebodypostprocesshook' => $extensionClassesPath . 'Hook/TemplateModuleBodyPostProcessHook.php',
);
?>